# Generated by Django 4.2.1 on 2023-05-29 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clgstore',
            name='about',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='clgstore',
            name='image',
            field=models.ImageField(null=True, upload_to='dep'),
        ),
    ]
