# Generated by Django 4.2.1 on 2023-05-29 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_clgstore_about_clgstore_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clgstore',
            name='about',
        ),
        migrations.RemoveField(
            model_name='clgstore',
            name='image',
        ),
    ]
