# Generated by Django 4.2.1 on 2023-05-29 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_clgstore_about_remove_clgstore_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='dep')),
                ('dep_name', models.CharField(max_length=100)),
                ('about', models.TextField()),
            ],
        ),
    ]
