# Generated by Django 4.2.1 on 2023-06-02 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_course_dpt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Dpt',
        ),
    ]
